#
#
# MoreSurvival by GamerCoder215
#
# v1.0.0

# Message Used to welcome/greet players
# Use %player% for username, %uuid% for player's UUID
WelcomeMessage: Welcome to the Server, %player%!

# Message Used to say goodbye to players that leave the server
LeaveMessage: Goodbye %player%!